### ISSUE TITLE
Implement Frontend project structure to talk with the backend

### ISSUE THREAD

**Issue by rvalenciano** [safetrustcr/Frontend#58]
# [Frontend] - General - Implement Frontend project structure to talk with the backend

Set up the React frontend project structure with GraphQL integration to communicate with our Hasura backend.

## Problem
We need to:
- Set up a clean, scalable React project structure
- Configure GraphQL client for Hasura
- Implement Firebase authentication integration
- Set up proper TypeScript configurations
- Establish coding standards and patterns

### Project Structure
```
src/
├── components/          # Shared/common components
│   ├── layout/         # Layout components
│   ├── forms/          # Form components
│   └── ui/             # UI components (buttons, inputs, etc.)
├── features/           # Feature-based modules
│   ├── auth/          # Authentication related
│   ├── apartments/    # Apartment management
│   ├── bids/         # Bid management
│   └── escrow/       # Escrow management
├── graphql/           # GraphQL operations
│   ├── mutations/
│   ├── queries/
│   ├── subscriptions/
│   └── generated/     # Generated types
├── hooks/             # Custom hooks
├── utils/             # Utility functions
├── services/          # External service integrations
├── config/            # Configuration files
└── types/             # TypeScript type definitions
```

### Required Dependencies
```json
{
  "dependencies": {
    "@apollo/client": "^3.8.x",
    "@graphql-codegen/cli": "^5.x.x",
    "graphql": "^16.x.x",
    "firebase": "^10.x.x",
    "react": "^18.x.x",
    "react-router-dom": "^6.x.x",
    "typescript": "^5.x.x",
    "@tanstack/react-query": "^5.x.x",
    "tailwindcss": "^3.x.x"
  }
}
```

#### GraphQL Codegen
```yaml
# codegen.yml
schema:
  - ${REACT_APP_HASURA_ENDPOINT}:
      headers:
        x-hasura-admin-secret: ${REACT_APP_HASURA_ADMIN_SECRET}
documents: 'src/**/*.graphql.ts'
generates:
  src/graphql/generated/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      withHooks: true
```

#### Apollo Client Setup
```typescript
// src/config/apollo.ts
import { ApolloClient, InMemoryCache, createHttpLink } from '@apollo/client';
import { setContext } from '@apollo/client/link/context';
import { getAuth } from 'firebase/auth';

const httpLink = createHttpLink({
  uri: process.env.REACT_APP_HASURA_ENDPOINT,
});

const authLink = setContext(async (_, { headers }) => {
  const auth = getAuth();
  const token = await auth.currentUser?.getIdToken();

  return {
    headers: {
      ...headers,
      authorization: token ? `Bearer ${token}` : '',
    },
  };
});

export const client = new ApolloClient({
  link: authLink.concat(httpLink),
  cache: new InMemoryCache(),
});
```

#### Firebase Config
```typescript
// src/config/firebase.ts
import { initializeApp } from 'firebase/auth';

const firebaseConfig = {
  apiKey: process.env.REACT_APP_FIREBASE_API_KEY,
  authDomain: process.env.REACT_APP_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.REACT_APP_FIREBASE_PROJECT_ID,
};

export const app = initializeApp(firebaseConfig);
```

### Core Providers Setup
```typescript
// src/providers/AppProviders.tsx
import { ApolloProvider } from '@apollo/client';
import { BrowserRouter } from 'react-router-dom';
import { AuthProvider } from './AuthProvider';
import { client } from '../config/apollo';

export const AppProviders: React.FC<{ children: React.ReactNode }> = ({ 
  children 
}) => {
  return (
    <BrowserRouter>
      <ApolloProvider client={client}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </ApolloProvider>
    </BrowserRouter>
  );
};
```

### Authentication Provider
```typescript
// src/providers/AuthProvider.tsx
import { createContext, useContext, useEffect, useState } from 'react';
import { getAuth, onAuthStateChanged } from 'firebase/auth';
import { useApolloClient } from '@apollo/client';

const AuthContext = createContext<{
  user: any;
  loading: boolean;
}>({
  user: null,
  loading: true,
});

export const AuthProvider = ({ children }) => {
  const [user, setUser] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const client = useApolloClient();

  useEffect(() => {
    const auth = getAuth();
    return onAuthStateChanged(auth, async (user) => {
      setUser(user);
      setLoading(false);
      if (!user) {
        await client.resetStore();
      }
    });
  }, [client]);

  return (
    <AuthContext.Provider value={{ user, loading }}>
      {children}
    </AuthContext.Provider>
  );
};
```

## Implementation Steps

1. Project Setup
```bash
# Create project with Vite
npm create vite@latest safetrust-frontend -- --template react-ts

# Install dependencies
cd safetrust-frontend
npm install @apollo/client graphql firebase react-router-dom @tanstack/react-query

# Install dev dependencies
npm install -D @graphql-codegen/cli @graphql-codegen/typescript @graphql-codegen/typescript-operations @graphql-codegen/typescript-react-apollo tailwindcss postcss autoprefixer
```

2. Configure Environment
```env
VITE_HASURA_ENDPOINT=http://localhost:8080/v1/graphql
VITE_HASURA_WS_ENDPOINT=ws://localhost:8080/v1/graphql
VITE_FIREBASE_API_KEY=your-api-key
VITE_FIREBASE_AUTH_DOMAIN=your-domain
VITE_FIREBASE_PROJECT_ID=your-project-id
```

3. Setup GraphQL Code Generation
```bash
# Initialize codegen
npm run graphql-codegen init

# Generate types
npm run codegen
```

### File Naming
- Components: PascalCase (e.g., `UserProfile.tsx`)
- Hooks: camelCase with 'use' prefix (e.g., `useAuth.ts`)
- Utils: camelCase (e.g., `formatDate.ts`)
- GraphQL operations: camelCase (e.g., `getUserProfile.graphql.ts`)

### Import Order
1. React/External libraries
2. GraphQL operations
3. Components
4. Hooks
5. Utils
6. Types
7. Styles

### Component Structure
```typescript
// Example component structure
import { useQuery } from '@apollo/client';
import { GET_USER_PROFILE } from './graphql';
import { LoadingSpinner } from '../components';
import { useAuth } from '../hooks';
import { formatDate } from '../utils';
import type { User } from '../types';

export const UserProfile: React.FC = () => {
  // hooks
  // state
  // effects
  // handlers
  // render
};
```

## Success Criteria
- [ ] Project structure implemented
- [ ] GraphQL client configured
- [ ] Firebase authentication working
- [ ] Type generation working
- [ ] Coding standards documented
- [ ] Basic routing implemented
- [ ] Environment variables configured

## Additional Context
This structure supports:
- Feature-based organization
- Strong typing with GraphQL codegen
- Secure authentication flow
- Scalable component architecture
- Clean code practices

## Related Issues
- #XX Firebase Auth Integration
- #XX GraphQL Operations Setup

Would you like me to:
1. Add more detailed component examples?
2. Show routing configuration?
3. Add error boundary setup?
4. Include test configuration?
